In [ ]:
class A:
  def __init__(self):
    print('this is the init message')

  def __call__(slef):
    print('called by __call__ constructor')

  def __new__(cls):
    print('called by new constructor ')
    return super(A, cls).__new__(cls)

a = A()

called by new constructor
this is the init message

In [ ]:
a()

called by __call__ constructor

In [ ]:
def infinite_sequence():
    n = 0
    while True:
        yield n
        n += 1

g = infinite_sequence()

In [ ]:
import pandas as pd

data = {
    'Date': ['2026-01-01', '2026-01-01', '2026-01-02', '2026-01-02'],
    'Branch': ['North', 'South', 'North', 'North'],
    'Category': ['Electronics', 'Clothing', 'Electronics', 'Clothing'],
    'Revenue': [1200, 800, 1500, 400]
}
df = pd.DataFrame(data)

In [ ]:
df

         Date Branch     Category  Revenue
0  2026-01-01  North  Electronics     1200
1  2026-01-01  South     Clothing      800
2  2026-01-02  North  Electronics     1500
3  2026-01-02  North     Clothing      400

In [ ]:
pivit_df = df.pivot_table(columns='Date',aggfunc='sum',fill_value=0,values='Revenue',index=['Branch','Category'])

In [ ]:
from sklearn.ensemble import RandomForestClassifier , BaggingClassifier , BaggingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , classification_report , r2_score , mean_squared_error
import numpy as np
import pandas as pd
from sklearn.svm import SVC , SVR
from sklearn.linear_model import LogisticRegression , LinearRegression
from sklearn.tree import DecisionTreeClassifier , DecisionTreeRegressor ,plot_tree
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
import pandas as pd

data = {
    'Customer_ID': [101, 102, 101, 103, 102, 101, 102, 104, 101, 104],
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Desk', 'Keyboard', 'RAM', 'Monitor', 'Phone', 'Cable', 'Headphones'],
    'Price': [1200, 25, 300, 450, 80, 150, 280, 800, 15, 120]
}

df_sales = pd.DataFrame(data)

In [ ]:
df_sales.groupby('Customer_ID').filter(lambda x : len(x)>3 and x['Price'].sum()>500)

In [ ]:
# second method more effective
customer_stats = df_sales.groupby('Customer_ID').agg(
    total_spend=('Price','sum'),
    count =('Price','count')
    )

filtered = customer_stats[(customer_stats['total_spend'] > 500)&(customer_stats['count'] >3)]
result = filtered['total_spend']

In [ ]:
result

In [ ]:
# Your task is to find any employees who have overlapping project dates.
import pandas as pd

data = {
    'Emp_ID': [1, 1, 2, 2, 3, 3],
    'Project': ['Proj_A', 'Proj_B', 'Proj_C', 'Proj_D', 'Proj_E', 'Proj_F'],
    'Start_Date': ['2026-01-01', '2026-01-15', '2026-02-01', '2026-03-01', '2026-04-01', '2026-05-01'],
    'End_Date':   ['2026-01-20', '2026-02-15', '2026-02-20', '2026-04-01', '2026-04-15', '2026-06-01']
}

df_projects = pd.DataFrame(data)
# Converting to datetime objects to help you out
df_projects['Start_Date'] = pd.to_datetime(df_projects['Start_Date'])
# Note: It's 2026 currently, so the dates match the current year context.
df_projects['End_Date'] = pd.to_datetime(df_projects['End_Date'])

In [ ]:
df_projects

   Emp_ID Project  Start_Date   End_Date
0       1  Proj_A  2026-01-01 2026-01-20
1       1  Proj_B  2026-01-15 2026-02-15
2       2  Proj_C  2026-02-01 2026-02-20
3       2  Proj_D  2026-03-01 2026-04-01
4       3  Proj_E  2026-04-01 2026-04-15
5       3  Proj_F  2026-05-01 2026-06-01

In [ ]:
# 1. Sort by Employee and Start Date
df_sorted = df_projects.sort_values(by=['Emp_ID', 'Start_Date'])

# 2. Get the previous project's End Date for each employee
df_sorted['Prev_End_Date'] = df_sorted.groupby('Emp_ID')['End_Date'].shift(1)

# 3. Check for overlaps (Current Start <= Previous End)
overlap_condition = df_sorted['Start_Date'] <= df_sorted['Prev_End_Date']

# 4. Filter the dataframe and get unique Employee IDs
overlapping_employees = df_sorted[overlap_condition]

print("Employees with schedule conflicts:", overlapping_employees)

Employees with schedule conflicts:    Emp_ID Project  Start_Date   End_Date Prev_End_Date
1       1  Proj_B  2026-01-15 2026-02-15    2026-01-20

In [ ]:
overlapping_employees

array([1])

In [ ]:
df_sorted

   Emp_ID Project  Start_Date   End_Date Prev_End_Date
0       1  Proj_A  2026-01-01 2026-01-20           NaT
1       1  Proj_B  2026-01-15 2026-02-15    2026-01-20
2       2  Proj_C  2026-02-01 2026-02-20           NaT
3       2  Proj_D  2026-03-01 2026-04-01    2026-02-20
4       3  Proj_E  2026-04-01 2026-04-15           NaT
5       3  Proj_F  2026-05-01 2026-06-01    2026-04-15

In [85]:
import pandas as pd

data = {
    'Department': ['Sales', 'Engineering', 'Marketing'],
    'Jan_Budget': [5000, 12000, 7000],
    'Feb_Budget': [5500, 12500, 6000],
    'Mar_Budget': [6000, 13000, 8000]
}

df_budget = pd.DataFrame(data)

In [86]:
df_budget

    Department  Jan_Budget  Feb_Budget  Mar_Budget
0        Sales        5000        5500        6000
1  Engineering       12000       12500       13000
2    Marketing        7000        6000        8000

In [95]:
df_melted = df_budget.melt(id_vars=['Department'], var_name='Month', value_name='Budget')
print(df_melted)

    Department       Month  Budget
0        Sales  Jan_Budget    5000
1  Engineering  Jan_Budget   12000
2    Marketing  Jan_Budget    7000
3        Sales  Feb_Budget    5500
4  Engineering  Feb_Budget   12500
5    Marketing  Feb_Budget    6000
6        Sales  Mar_Budget    6000
7  Engineering  Mar_Budget   13000
8    Marketing  Mar_Budget    8000

In [96]:
import pandas as pd

data = {
    'Week': [1, 2, 3, 4, 5],
    'Revenue': [10000, 12000, 11000, 15000, 14500]
}

df_revenue = pd.DataFrame(data)

In [97]:
# You need to calculate the absolute difference in revenue compared to the previous week, as well as the percentage growth week-over-week.
df_revenue['Previous_Revenue'] = df_revenue['Revenue'].shift(1)
df_revenue['Difference'] = df_revenue['Revenue'] - df_revenue['Previous_Revenue']
df_revenue['Percentage_Growth'] = (df_revenue['Revenue'] - df_revenue['Previous_Revenue']) / df_revenue['Previous_Revenue'] * 100

In [98]:
df_revenue

   Week  Revenue  Previous_Revenue  Difference  Percentage_Growth
0     1    10000               NaN         NaN                NaN
1     2    12000           10000.0      2000.0          20.000000
2     3    11000           12000.0     -1000.0          -8.333333
3     4    15000           11000.0      4000.0          36.363636
4     5    14500           15000.0      -500.0          -3.333333

In [ ]:
# df_revenue['Revenue'].diff()
# df_revenue['Revenue'].pct_change()* 100

In [99]:
import pandas as pd

data = {
    'User_ID': [1, 2, 3, 4, 5, 6],
    'Status': [' Full-time ', 'fulltime', 'Part-Time', 'part-time  ', 'FULL-TIME', ' Unemployed']
}

df_survey = pd.DataFrame(data)

In [104]:
df_survey['Status'] = df_survey['Status'].str.strip().str.lower().str.replace('fulltime','full-time').str.title()

In [105]:
df_survey

   User_ID      Status
0        1   Full-Time
1        2   Full-Time
2        3   Part-Time
3        4   Part-Time
4        5   Full-Time
5        6  Unemployed

In [106]:
import pandas as pd

df_employees = pd.DataFrame({
    'Emp_ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['Sales', 'Engineering', 'Sales', 'HR']
})

df_targets = pd.DataFrame({
    'Department': ['Sales', 'Marketing'],
    'Target': [10000, 5000]
})

In [108]:
df_employees.merge(df_targets,left_on='Department',right_on='Department',how='left').fillna(0)

   Emp_ID     Name   Department   Target
0       1    Alice        Sales  10000.0
1       2      Bob  Engineering      0.0
2       3  Charlie        Sales  10000.0
3       4    David           HR      0.0

In [109]:
import pandas as pd

data = {
    'Department': ['HR', 'HR', 'HR', 'IT', 'IT', 'IT', 'IT', 'Sales', 'Sales'],
    'Name': ['Amelia', 'Ben', 'Chloe', 'Daniel', 'Emily', 'Fred', 'Grace', 'Henry', 'Ian'],
    'Salary': [60000, 55000, 65000, 80000, 85000, 75000, 90000, 70000, 72000]
}

df_salaries = pd.DataFrame(data)

In [118]:
# Pandas code to filter df_salaries so that it only contains the rows of the top 2 highest-earning employees for each Department.
df_top_employees = df_salaries.sort_values(by=['Department','Salary'],ascending=False).groupby('Department').head(2)

In [119]:
df_top_employees

  Department    Name  Salary
8      Sales     Ian   72000
7      Sales   Henry   70000
6         IT   Grace   90000
4         IT   Emily   85000
2         HR   Chloe   65000
0         HR  Amelia   60000

In [120]:
import pandas as pd

data = {
    'Order_ID': [501, 502, 503, 504, 505],
    'Customer': ['Alex', 'Brian', 'Catherine', 'Delta', 'Echo'],
    'Order_Value': [35, 150, 45, 210, 85]
}

df_orders = pd.DataFrame(data)

In [121]:
df_orders

   Order_ID   Customer  Order_Value
0       501       Alex           35
1       502      Brian          150
2       503  Catherine           45
3       504      Delta          210
4       505       Echo           85

In [124]:
import numpy as np
df_orders['Tier'] = np.where(df_orders['Order_Value'] < 50, 'Bronze' , np.where( (df_orders['Order_Value'] >= 50) & (df_orders['Order_Value'] <= 150),'Silver','Gold'))

In [125]:
df_orders

   Order_ID   Customer  Order_Value    Tier
0       501       Alex           35  Bronze
1       502      Brian          150  Silver
2       503  Catherine           45  Bronze
3       504      Delta          210    Gold
4       505       Echo           85  Silver

In [126]:
pd.cut(df_orders['Order_Value'],bins=[-np.inf ,50 , 150 , np.inf],labels=['Bronze','Silver','Gold'])

0    Bronze
1    Silver
2    Bronze
3      Gold
4    Silver
Name: Order_Value, dtype: category
Categories (3, object): ['Bronze' < 'Silver' < 'Gold']

In [127]:
import pandas as pd

data = {
    'User_ID': [10, 20, 10, 30, 20, 10],
    'Timestamp': ['2026-05-18 09:00:00', '2026-05-18 09:15:00', '2026-05-18 10:00:00',
                  '2026-05-18 10:30:00', '2026-05-18 11:00:00', '2026-05-18 11:30:00'],
    'Source': ['Google', 'Organic', 'Twitter', 'Direct', 'Google', 'AdWords']
}

df_visits = pd.DataFrame(data)
df_visits['Timestamp'] = pd.to_datetime(df_visits['Timestamp'])

In [130]:
# You want to extract a DataFrame that shows only the very first visit for each user, so you can analyze how new users are arriving.
df_visits.sort_values(by='Timestamp').groupby('User_ID').first()

                  Timestamp   Source
User_ID
10      2026-05-18 09:00:00   Google
20      2026-05-18 09:15:00  Organic
30      2026-05-18 10:30:00   Direct